# SPDX-License-Identifier: AGPL-3.0-only
version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      kotlin-and-compose:
        patterns:
          - "org.jetbrains.kotlin*"
          - "androidx.compose*"
      androidx:
        patterns:
          - "androidx.*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
